FROM python:3.11-slim

WORKDIR /app

ENV PYTHONPATH=/app

COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt


COPY ./app ./app
# COPY ./tests ./tests
# COPY ./alembic.ini ./alembic.ini
# COPY ./migrations ./migrations
# COPY ./pytest.ini ./pytest.ini



CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]