class ResumeErrorCode:
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    EMPTY_PDF = "EMPTY_PDF"
    NO_READABLE_TEXT_FOUND = "NO_READABLE_TEXT_FOUND"
    PDF_TEXT_EXTRACTION_FAILED = "PDF_TEXT_EXTRACTION_FAILED"