"""create resume analysis table

Revision ID: 6ad7543f6989
Revises: ffcab271efd6
Create Date: 2026-06-27 04:46:45.231168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ad7543f6989'
down_revision: Union[str, Sequence[str], None] = 'ffcab271efd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profile_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skills_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('education_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('projects_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('resume_completeness', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('keyword_match_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('missing_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('matched_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('suggestions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('strengths', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('weaknesses', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('analysis_version', sa.String(length=20), nullable=False),
    sa.Column('analysis_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_analysis_id'), 'resume_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_resume_analysis_resume_id'), 'resume_analysis', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_analysis_resume_id'), table_name='resume_analysis')
    op.drop_index(op.f('ix_resume_analysis_id'), table_name='resume_analysis')
    op.drop_table('resume_analysis')
    # ### end Alembic commands ###
