"""upadate the resume table with pay_UUID

Revision ID: c77a1a292289
Revises: d7e7cbf37929
Create Date: 2026-06-24 11:26:46.206982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77a1a292289'
down_revision: Union[str, Sequence[str], None] = 'd7e7cbf37929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
