"""add resume_experience table

Revision ID: cf3293bedb08
Revises: 36c70cfa0792
Create Date: 2026-06-26 12:53:30.990872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3293bedb08'
down_revision: Union[str, Sequence[str], None] = '36c70cfa0792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_experiences_company_name'), 'resume_experiences', ['company_name'], unique=False)
    op.create_index(op.f('ix_resume_experiences_id'), 'resume_experiences', ['id'], unique=False)
    op.create_index(op.f('ix_resume_experiences_job_title'), 'resume_experiences', ['job_title'], unique=False)
    op.create_index(op.f('ix_resume_experiences_resume_id'), 'resume_experiences', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_experiences_resume_id'), table_name='resume_experiences')
    op.drop_index(op.f('ix_resume_experiences_job_title'), table_name='resume_experiences')
    op.drop_index(op.f('ix_resume_experiences_id'), table_name='resume_experiences')
    op.drop_index(op.f('ix_resume_experiences_company_name'), table_name='resume_experiences')
    op.drop_table('resume_experiences')
    # ### end Alembic commands ###
