"""create a resueme education table 

Revision ID: f2cab22d1e63
Revises: c77a1a292289
Create Date: 2026-06-24 11:34:46.902886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cab22d1e63'
down_revision: Union[str, Sequence[str], None] = 'c77a1a292289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_educations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_educations_id'), 'resume_educations', ['id'], unique=False)
    op.create_index(op.f('ix_resume_educations_institution'), 'resume_educations', ['institution'], unique=False)
    op.create_index(op.f('ix_resume_educations_resume_id'), 'resume_educations', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_educations_resume_id'), table_name='resume_educations')
    op.drop_index(op.f('ix_resume_educations_institution'), table_name='resume_educations')
    op.drop_index(op.f('ix_resume_educations_id'), table_name='resume_educations')
    op.drop_table('resume_educations')
    # ### end Alembic commands ###
