"""add refresh token revoke fields

Revision ID: 3fab60f99f44
Revises: bbea56dd8457
Create Date: 2026-06-12 04:35:28.286871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fab60f99f44'
down_revision: Union[str, Sequence[str], None] = 'bbea56dd8457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('refresh_tokens', 'expire_at')
    op.drop_column('refresh_tokens', 'is_revoke')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_revoke', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('expire_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'revoked_at')
    op.drop_column('refresh_tokens', 'is_revoked')
    op.drop_column('refresh_tokens', 'expires_at')
    # ### end Alembic commands ###
