"""fix refresh token is_revoke column

Revision ID: bbea56dd8457
Revises: 72ac82c5bda3
Create Date: 2026-06-10 14:23:27.456525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbea56dd8457'
down_revision: Union[str, Sequence[str], None] = '72ac82c5bda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_revoke', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'is_revoke')
    # ### end Alembic commands ###
